<?php

namespace App\Filament\Tenant\Resources;

use App\Filament\Forms\Components\MoneyInput;
use App\Filament\Tenant\Resources\InvoiceResource\Pages;
use App\Filament\Tenant\Resources\InvoiceResource\RelationManagers\ItemsRelationManager;
use App\Filament\Tenant\Resources\InvoiceResource\RelationManagers\PaymentsRelationManager;
use App\Models\Booking;
use App\Models\Customer;
use App\Models\Invoice;
use App\Notifications\InvoiceEmailed;
use App\Notifications\InvoicePaymentLink;
use App\Services\Mail\TenantMailer;
use App\Support\Money;
use BackedEnum;
use Barryvdh\DomPDF\Facade\Pdf;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\EditAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\ViewEntry;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;
use Throwable;
use UnitEnum;

class InvoiceResource extends Resource
{
    protected static ?string $model = Invoice::class;

    protected static ?string $navigationLabel = 'Invoices';

    protected static BackedEnum|string|null $navigationIcon = 'heroicon-o-document-text';

    protected static UnitEnum|string|null $navigationGroup = 'CRM';

    protected static ?int $navigationSort = 7;

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Select::make('booking_id')
                ->relationship('booking', 'trip_name')
                ->searchable()
                ->preload()
                ->required()
                ->live()
                ->afterStateUpdated(function (Get $get, Set $set): void {
                    $booking = Booking::query()->find($get('booking_id'));

                    if ($booking) {
                        $set('customer_id', $booking->customer_id);
                    }
                }),
            Select::make('customer_id')
                ->relationship('customer', 'name')
                ->searchable()
                ->preload()
                ->required()
                ->createOptionForm(CustomerResource::quickCreateSchema())
                ->createOptionAction(fn (Action $action) => $action
                    ->visible(fn (): bool => (bool) auth('tenant')->user()?->can('create', Customer::class))
                    ->modalHeading('Add guest customer')),
            TextInput::make('invoice_no')
                ->label('Invoice number')
                ->readOnly()
                ->helperText('Auto-generated when the invoice is created.')
                ->hiddenOn('create'),
            MoneyInput::make('amount')
                ->label('Amount')
                ->minValue(0)
                ->required(),
            MoneyInput::make('tax')
                ->minValue(0)
                ->default(0),
            MoneyInput::make('discount')
                ->minValue(0)
                ->default(0),
            MoneyInput::make('total')
                ->label('Total')
                ->minValue(0)
                ->required(),
            Select::make('status')->options([
                'draft' => 'Draft',
                'issued' => 'Issued',
                'paid' => 'Paid',
                'partially_paid' => 'Partially paid',
                'overdue' => 'Overdue',
                'cancelled' => 'Cancelled',
            ])->required(),
            DatePicker::make('due_date')->label('Due date')->native(false),
            Section::make('Payments')
                ->visibleOn('edit')
                ->schema([
                    Placeholder::make('paid_display')->label('Amount paid')->content(fn (Invoice $record): string => Money::format($record->paidAmount(), $record->currency)),
                    Placeholder::make('balance_display')->label('Balance due')->content(fn (Invoice $record): string => Money::format($record->balanceDue(), $record->currency)),
                ])
                ->columns(1),
            Section::make('Gift voucher purchase')
                ->description('This invoice was generated by a customer buying a gift voucher through the portal. See the Items tab for who each voucher was sent to.')
                ->visible(fn (?Invoice $record): bool => $record?->purpose === 'gift_voucher_purchase')
                ->schema([
                    Placeholder::make('purchaser_name_display')->label('Purchaser')->content(fn (Invoice $record): string => $record->purchaserName() ?? '—'),
                    Placeholder::make('purchaser_email_display')->label('Email')->content(fn (Invoice $record): string => $record->purchaser_email ?? '—'),
                    Placeholder::make('purchaser_phone_display')->label('Phone')->content(fn (Invoice $record): string => $record->purchaser_phone ?? '—'),
                    Placeholder::make('recipient_count_display')->label('Recipients')->content(fn (Invoice $record): string => (string) $record->items()->count()),
                ])
                ->columns(2),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table->columns([
            TextColumn::make('customer.name')->label('Name')->searchable()->sortable(),
            TextColumn::make('customer.email')->label('Email')->searchable()
                ->toggleable(isToggledHiddenByDefault: true),
            TextColumn::make('invoice_no')->label('Invoice number')->searchable()->sortable(),
            TextColumn::make('purpose')
                ->label('Transaction type')
                ->badge()
                ->color(fn (?string $state): string => $state === 'gift_voucher_purchase' ? 'warning' : 'gray')
                ->formatStateUsing(fn (?string $state): string => $state === 'gift_voucher_purchase' ? 'Gift voucher' : 'Standard')
                ->sortable(),
            TextColumn::make('created_at')->label('Date')->date()->sortable(),
            TextColumn::make('total')->label('Amount')->money(fn (Invoice $record): string => $record->currency, divideBy: 100)->sortable(),
            TextColumn::make('mode')
                ->label('Mode')
                ->state(fn (Invoice $record): ?string => $record->latestPaymentMethod())
                ->formatStateUsing(fn (?string $state): string => $state ? Str::headline($state) : '—')
                ->badge()
                ->color('gray'),
            TextColumn::make('status')->badge()->sortable(),
            TextColumn::make('booking.trip_name')->label('Booking')->searchable()
                ->toggleable(isToggledHiddenByDefault: true),
            TextColumn::make('due_date')->date()->sortable()
                ->toggleable(isToggledHiddenByDefault: true),
        ])
            ->defaultSort('created_at', 'desc')
            ->filters([
                SelectFilter::make('status')->options([
                    'draft' => 'Draft',
                    'issued' => 'Issued',
                    'paid' => 'Paid',
                    'partially_paid' => 'Partially paid',
                    'overdue' => 'Overdue',
                    'cancelled' => 'Cancelled',
                ]),
                SelectFilter::make('purpose')
                    ->label('Transaction type')
                    ->options([
                        'gift_voucher_purchase' => 'Gift voucher',
                        'standard' => 'Standard',
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return match ($data['value'] ?? null) {
                            'gift_voucher_purchase' => $query->where('purpose', 'gift_voucher_purchase'),
                            'standard' => $query->where(fn (Builder $q) => $q->whereNull('purpose')->orWhere('purpose', '!=', 'gift_voucher_purchase')),
                            default => $query,
                        };
                    }),
            ])
            ->recordActions([
                ActionGroup::make([
                    ...static::rowActions(),
                    EditAction::make(),
                ])
                    ->label('Actions')
                    ->icon('heroicon-m-ellipsis-vertical')
                    ->color('gray')
                    ->size('sm')
                    ->tooltip('Actions'),
            ]);
    }

    /**
     * Shared between the table's row action menu and the View page's header actions, so the two
     * never drift out of sync on what an invoice can be acted on with.
     *
     * @return array<Action>
     */
    public static function rowActions(): array
    {
        return [
            Action::make('downloadPdf')
                ->label('Download PDF')
                ->icon('heroicon-o-arrow-down-tray')
                ->action(function (Invoice $record) {
                    $record->loadMissing(['tenant', 'customer', 'booking']);

                    try {
                        $output = Pdf::loadView('pdf.invoice', ['invoice' => $record])->output();
                    } catch (Throwable $e) {
                        Log::error('Invoice PDF generation failed.', ['invoice_id' => $record->id, 'message' => $e->getMessage()]);
                        Notification::make()->title('Could not generate the PDF')->danger()->send();

                        return null;
                    }

                    return response()->streamDownload(
                        fn () => print ($output),
                        "{$record->invoice_no}.pdf",
                    );
                }),
            Action::make('emailInvoice')
                ->label('Email invoice')
                ->icon('heroicon-o-envelope')
                ->requiresConfirmation()
                ->modalDescription(fn (Invoice $record): string => "Email a PDF copy of this invoice to {$record->customer?->email}?")
                ->action(function (Invoice $record): void {
                    $sent = app(TenantMailer::class)->send($record->tenant_id, $record->customer, new InvoiceEmailed($record));

                    if (! $sent) {
                        Notification::make()->title('Invoice failed to send')->body('Check the tenant\'s mail settings.')->danger()->send();

                        return;
                    }

                    Notification::make()->title('Invoice emailed')->success()->send();
                }),
            Action::make('sendPaymentLink')
                ->label('Send payment link')
                ->icon('heroicon-o-link')
                ->visible(fn (Invoice $record): bool => $record->balanceDue() > 0 && $record->customer?->email !== null)
                ->requiresConfirmation()
                ->modalDescription(fn (Invoice $record): string => "Email a no-login payment link for this invoice to {$record->customer?->email}?")
                ->action(function (Invoice $record): void {
                    $url = URL::temporarySignedRoute('public.pay.show', now()->addDays(14), ['invoice' => $record->id]);

                    $sent = app(TenantMailer::class)->send($record->tenant_id, $record->customer, new InvoicePaymentLink($record, $url));

                    if (! $sent) {
                        Notification::make()->title('Payment link failed to send')->body('Check the tenant\'s mail settings.')->danger()->send();

                        return;
                    }

                    Notification::make()->title('Payment link sent')->success()->send();
                }),
        ];
    }

    public static function infolist(Schema $schema): Schema
    {
        return $schema->components([
            ViewEntry::make('detail')
                ->view('filament.invoices.detail')
                ->columnSpanFull(),
        ]);
    }

    public static function getRelations(): array
    {
        return [
            ItemsRelationManager::class,
            PaymentsRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListInvoices::route('/'),
            'create' => Pages\CreateInvoice::route('/create'),
            'view' => Pages\ViewInvoice::route('/{record}'),
            'edit' => Pages\EditInvoice::route('/{record}/edit'),
        ];
    }
}
