@php
    use Filament\Support\Enums\IconSize;
    use Illuminate\Support\Str;

    $record = $getRecord();
    $isTenantStaff = auth('tenant')->check();
    $fromLabel = $isTenantStaff ? 'From' : 'Billed by';
    $fromName = $isTenantStaff ? $record->customer?->name : $record->tenant?->name;
    $fromEmail = $isTenantStaff ? $record->customer?->email : null;
    $fromPhone = $isTenantStaff ? $record->customer?->phone : null;

    $statusColors = [
        'paid' => 'success',
        'overdue' => 'danger',
        'partially_paid' => 'warning',
        'cancelled' => 'gray',
        'draft' => 'gray',
    ];
    $statusColor = $statusColors[$record->status] ?? 'info';

    $money = fn (int $cents): string => \Illuminate\Support\Number::currency($cents / 100, $record->currency);

    $giftVoucherApplied = $record->giftVoucherAppliedAmount();
    $balanceDue = $record->balanceDue();

    // Every card below is a real <x-filament::section>, every pill a real <x-filament::badge>,
    // every icon a real <x-filament::icon> — the same Blade components Filament's own Section/
    // TextColumn/IconEntry render with. That's what makes the background, borders, text color
    // and icons follow the panel's actual theme (including dark mode) instead of a fixed palette:
    // Filament panels only load Filament's own precompiled CSS, not this app's Tailwind build, so
    // any *custom* Tailwind utility class used here would have no matching rule — but these
    // component tags render Filament's own already-compiled classes, which do exist.
    //
    // Structural spacing/layout (flex rows, table cells) has no Filament-component equivalent, so
    // it stays inline; text left uncolored inherits the panel's default (light/dark-aware) text
    // color, and "muted" text dims that inherited color via opacity rather than a fixed gray so it
    // still reads correctly in dark mode.
    $muted = 'opacity:.6;font-size:14px;';
    $rowBetween = 'display:flex;align-items:center;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--gray-200);';
    $rowBetweenLast = 'display:flex;align-items:center;justify-content:space-between;padding:10px 0;';
    $th = 'padding:0 0 8px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.03em;opacity:.5;';
    $thRight = $th.'text-align:right;';
    $td = 'padding:8px 0;border-top:1px solid var(--gray-200);font-size:14px;';
    $tdMuted = $td.'opacity:.6;';
    $tdRight = $td.'text-align:right;';
@endphp

<div style="display:flex;flex-direction:column;gap:24px;">
    {{-- Header --}}
    <x-filament::section>
        <div style="display:flex;flex-wrap:wrap;align-items:center;gap:10px;">
            <h2 style="margin:0;font-size:18px;font-weight:700;">
                {{ $fromName ?? $record->invoice_no }} &ndash; {{ $record->created_at?->format('d M Y') }}
            </h2>
            <x-filament::badge :color="$statusColor">
                {{ ucfirst(str_replace('_', ' ', $record->status)) }}
            </x-filament::badge>
        </div>
        <p style="margin:6px 0 0;{{ $muted }}">Invoice number: {{ $record->invoice_no }}</p>
    </x-filament::section>

    @if ($record->purpose === 'gift_voucher_purchase')
        {{-- Gift voucher purchase --}}
        <x-filament::section
            heading="Gift voucher purchase"
            description="This invoice was generated by a customer buying a gift voucher through the portal. See the Items tab for who each voucher was sent to."
        >
            <div style="display:flex;flex-wrap:wrap;gap:24px;">
                <div>
                    <div style="font-size:11px;font-weight:600;text-transform:uppercase;opacity:.5;">Purchaser</div>
                    <div style="margin-top:2px;font-size:14px;">{{ $record->purchaserName() ?? '—' }}</div>
                </div>
                <div>
                    <div style="font-size:11px;font-weight:600;text-transform:uppercase;opacity:.5;">Email</div>
                    <div style="margin-top:2px;font-size:14px;">{{ $record->purchaser_email ?? '—' }}</div>
                </div>
                <div>
                    <div style="font-size:11px;font-weight:600;text-transform:uppercase;opacity:.5;">Phone</div>
                    <div style="margin-top:2px;font-size:14px;">{{ $record->purchaser_phone ?? '—' }}</div>
                </div>
            </div>
        </x-filament::section>
    @endif

    {{-- From / Billed by --}}
    <x-filament::section :heading="$fromLabel">
        <p style="margin:0;font-size:14px;font-weight:600;">{{ $fromName ?? '—' }}</p>
        @if ($fromEmail || $fromPhone)
            <div style="display:flex;flex-wrap:wrap;gap:20px;margin-top:12px;padding-top:12px;border-top:1px solid var(--gray-200);{{ $muted }}">
                @if ($fromEmail)
                    <span style="display:inline-flex;align-items:center;gap:6px;">
                        <x-filament::icon icon="heroicon-o-envelope" :size="IconSize::Small" />
                        {{ $fromEmail }}
                    </span>
                @endif
                @if ($fromPhone)
                    <span style="display:inline-flex;align-items:center;gap:6px;">
                        <x-filament::icon icon="heroicon-o-phone" :size="IconSize::Small" />
                        {{ $fromPhone }}
                    </span>
                @endif
            </div>
        @endif
    </x-filament::section>

    {{-- Transaction information --}}
    @if ($record->items->isNotEmpty())
        <x-filament::section heading="Transaction information">
            <div style="overflow-x:auto;">
                <table style="width:100%;border-collapse:collapse;">
                    <thead>
                        <tr>
                            <th style="{{ $th }}">Item</th>
                            <th style="{{ $th }}">Unit price</th>
                            <th style="{{ $th }}">Quantity</th>
                            <th style="{{ $thRight }}">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($record->items as $item)
                            <tr>
                                <td style="{{ $td }}">{{ $item->description }}</td>
                                <td style="{{ $tdMuted }}">{{ $money($item->unit_price) }}</td>
                                <td style="{{ $tdMuted }}">{{ $item->qty }}</td>
                                <td style="{{ $tdRight }}">{{ $money($item->total) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3" style="padding:10px 0 0;text-align:right;font-size:14px;font-weight:700;border-top:2px solid var(--gray-300);">Total</td>
                            <td style="padding:10px 0 0;text-align:right;font-size:14px;font-weight:700;border-top:2px solid var(--gray-300);">{{ $money($record->total) }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </x-filament::section>
    @endif

    {{-- Order summary --}}
    <x-filament::section heading="Order summary">
        <div style="{{ $rowBetween }}">
            <span style="{{ $muted }}">Subtotal</span>
            <span style="font-size:14px;">{{ $money($record->amount) }}</span>
        </div>
        @if ($record->discount > 0)
            <div style="{{ $rowBetween }}">
                <span style="{{ $muted }}">Discount</span>
                <span style="font-size:14px;">-{{ $money($record->discount) }}</span>
            </div>
        @endif
        @if ($record->tax > 0)
            <div style="{{ $rowBetween }}">
                <span style="{{ $muted }}">Tax</span>
                <span style="font-size:14px;">{{ $money($record->tax) }}</span>
            </div>
        @endif
        @if ($giftVoucherApplied > 0)
            <div style="{{ $rowBetween }}">
                <span style="{{ $muted }}">Gift voucher applied</span>
                <span style="font-size:14px;">-{{ $money($giftVoucherApplied) }}</span>
            </div>
        @endif
        <div style="{{ $rowBetween }}">
            <span style="font-size:14px;font-weight:700;">Total</span>
            <span style="font-size:14px;font-weight:700;">{{ $money($record->total) }}</span>
        </div>
        <div style="{{ $rowBetweenLast }}">
            <span style="font-size:14px;font-weight:700;">Balance due</span>
            <x-filament::badge :color="$balanceDue > 0 ? 'danger' : 'success'">
                {{ $money(max($balanceDue, 0)) }}
            </x-filament::badge>
        </div>
    </x-filament::section>

    {{-- Payments received --}}
    @if ($record->payments->isNotEmpty())
        <x-filament::section heading="Payments received">
            <div style="overflow-x:auto;">
                <table style="width:100%;border-collapse:collapse;">
                    <thead>
                        <tr>
                            <th style="{{ $th }}">Amount</th>
                            <th style="{{ $th }}">Method</th>
                            <th style="{{ $th }}">Type</th>
                            <th style="{{ $th }}">Status</th>
                            <th style="{{ $thRight }}">Paid at</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($record->payments as $payment)
                            <tr>
                                <td style="{{ $td }}">{{ $money($payment->amount) }}</td>
                                <td style="{{ $tdMuted }}">{{ Str::headline($payment->method) }}</td>
                                <td style="{{ $tdMuted }}">{{ Str::headline($payment->type) }}</td>
                                <td style="{{ $td }}">
                                    <x-filament::badge :color="match ($payment->status) {
                                        'completed' => 'success',
                                        'failed' => 'danger',
                                        'refunded' => 'gray',
                                        default => 'warning',
                                    }">
                                        {{ Str::headline($payment->status) }}
                                    </x-filament::badge>
                                </td>
                                <td style="{{ $tdRight }}opacity:.6;">{{ $payment->paid_at?->format('M j, Y H:i') }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </x-filament::section>
    @endif
</div>
